### ISSUE TITLE
Does anybody know the Default Wifi Password for EO Mini pro 2 - Broken QR Code

### ISSUE THREAD

**Issue by barrypearseburke** [twhittock/eo_mini#15]
Hi all. I know this is probably the wrong place, but a friend of mine has the EO mini pro2. Their home wifi got disconnected for a hour or so and the app got disconnected.

They went to try connecting again via the qr code, but the code had faded in the sun and is not scanning

Ive tried Enhancing the QR Code in photoshop, but the qr code still wont scan via the app. 
I am able to scan it with my iphone camera and it returns a code (some letters changed)
1 RU0yMTc4UEg= PA9IVUItMTc4MDg= M1AwVTRIPlRTNkFX 811baa67aeb6040ad40d27e95e036e200a3b9509844ac249a91fac0f4e48f971

My understanding was, all this qr did was allow you to connect to the wifi signal that the charger was putting out. EG eoHUB-17101
Does anybody know what the default wifi password so i can try that?

**Comment by seanmccabe** [comment]
Have you reached out to EO support?
They could likely advise, or failing that provide the QR code. I was under the belief it was unique for each unit.

**Comment by barrypearseburke** [comment]
They have, but they dont provide any support really. It with their support team , but no update in the last 2 weeks despite numerous calls

from playing around it seems like charger is offline, because it cant connect to the internet. The led is blue and goes to green when you plug it in, but nothing happens, the car doesnt charge 

Do you know if you scan your qr code with your normal camera, does it come out like that string ?

**Comment by twhittock** [comment]
Sorry about your trouble, but I don't see how this home assistant integration can help with this - the integration relies on the cloud service hosted by EO, rather than directly connecting to the charger's built-in wifi AP. I hope you find a solution.
