### ISSUE TITLE
Lock state unknown

### ISSUE THREAD

**Issue by gurmukhp** [twhittock/eo_mini#16]
## Version

Latest

## Describe the bug
I don't keep my EO Mini Pro 2 online all the time, I only really turn it on the day id like to charge. 

Today it has been on and a few automations were setup to lock and unlock the charger. 

Unfortunately for some reason, whilst the lock was unlocked, it never locked again. If I look at the history of the lock, it's been "unknown" for 20 hours. 

If I reload the integration, the lock state is correctly set. 

Is this because I turn the unit off when not in use?

**Comment by twhittock** [comment]
Hi, perhaps the integration has had some problem, and failed to connect to EO's servers? Were there any log messages?
