### ISSUE TITLE
Change charging rate

### ISSUE THREAD

**Issue by gurmukhp** [twhittock/eo_mini#8]
**Describe the solution you'd like**
Is it possible to change the charging rate of the EO Mini Pro 2? I don't have the option in the app but I know the EO installers have access to this.

**Comment by Paulholloway** [comment]
From what I recall of my installation, the charging rate of the EO is adjusted using a rotary switch - Step 5 
from:

[https://www.alternergy.co.uk/media/mageplaza/product_attachments/attachment_file/e/o/eo_mini_-_installation_user_guide_08_10_2019.pdf](url)

I did query the ability to adjust the charge current remotely with the EO team and they told me this was not possible.

**Comment by gurmukhp** [comment]
Thank you
