### ISSUE TITLE
Charging state 

### ISSUE THREAD

**Issue by gurmukhp** [twhittock/eo_mini#9]
Is it possible to add an update to this plugin to know when the charger is charging Vs not charging ? Maybe something like check the charging rate?

**Comment by Paulholloway** [comment]
Based on the entities already provided, might a derivative helper work (to identify a change in the consumption entity).  After which, you can set up an automation to detect instances of the change in consumption, and then toggle (helper) on/off accordingly.  It's a fairly indirect / aggircultural way of getting to the bottom of this, mind.  

Hope this helps.

**Comment by gurmukhp** [comment]
Nice workaround, thanks!
